# Generated by Django 2.1.4 on 2018-12-31 04:25

import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pyale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letting_type', models.CharField(max_length=50)),
                ('letting_start_date', models.DateField()),
                ('letting_end_date', models.DateField()),
                ('deposit', models.CharField(max_length=512)),
                ('deposit_refunded', models.BooleanField(blank=True, null=True)),
                ('deposit_refund_date', models.DateTimeField(blank=True, null=True)),
                ('total_letting_cost', models.CharField(help_text='Total Cost for the letting period', max_length=512)),
                ('service_charge', models.CharField(max_length=100)),
                ('payment_schedule', models.CharField(choices=[('Annual', 'annual'), ('Quarterly', 'quarterly'), ('Monthly', 'monthly')], help_text='Monthly, Quarterly or Annually', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.CharField(help_text='The amount to be paid per cycle e.g. the amount per month or per quarter', max_length=512)),
                ('payment_status', models.BooleanField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_cycle', models.CharField(max_length=100)),
                ('letting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Letting')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Residential', 'residential'), ('Commercial', 'commercial')], max_length=255)),
                ('total_cost', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('specs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None)),
                ('title', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
        migrations.AddField(
            model_name='letting',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property'),
        ),
        migrations.AddField(
            model_name='letting',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tenant'),
        ),
    ]
