# Generated by Django 2.1.4 on 2019-01-05 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pyale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='core.Property'),
        ),
    ]
