# Generated by Django 2.1.4 on 2019-01-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='active_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='letting',
            name='deposit_refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letting',
            name='letting_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='letting',
            name='letting_start_date',
            field=models.DateField(),
        ),
    ]
