# Generated by Django 2.1.4 on 2019-01-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190109_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='letting_duration',
            field=models.IntegerField(default='0', help_text='Letting period (must be in years)'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='letting_end_date',
            field=models.DateField(editable=False),
        ),
    ]
