# Generated by Django 2.1.4 on 2019-01-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letting',
            name='letting_type',
            field=models.CharField(default='Rent', max_length=50),
        ),
    ]
