# Generated by Django 2.1.4 on 2019-01-27 14:26

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_pyale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=255)),
                ('property_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('property_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Value of Property in Naira', max_digits=19, null=True)),
                ('current_rental_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('current_rental_value', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Rental Value of Property in Naira for current year', max_digits=19, null=True)),
                ('rental_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('rental_revenue', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Payable Revenue on property in Naira for current year', max_digits=19, null=True)),
                ('year', models.CharField(max_length=100)),
                ('net_revenue_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('net_revenue', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Net Revenue of Property in Naira for current year', max_digits=19, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'verbose_name': 'Tenant Payment Schedule', 'verbose_name_plural': 'Tenant Payment Schedules'},
        ),
        migrations.AlterModelOptions(
            name='propertydocument',
            options={'verbose_name': 'Property Document', 'verbose_name_plural': 'Property Documents'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertyrunningcosts',
            options={'verbose_name': 'Property Running Cost', 'verbose_name_plural': 'Property Running Costs'},
        ),
        migrations.AlterModelOptions(
            name='tenantdocument',
            options={'verbose_name': 'Tenant Document', 'verbose_name_plural': 'Tenant Documents'},
        ),
        migrations.AddField(
            model_name='tenantdocument',
            name='admin_only_access',
            field=models.BooleanField(default=False),
        ),
    ]
