# Generated by Django 2.1.4 on 2019-02-05 08:06

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_pyale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letting',
            old_name='total_letting_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='letting',
            old_name='letting_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='letting',
            old_name='letting_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='letting',
            old_name='letting_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='letting',
            old_name='letting_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='letting',
            name='total_letting_cost_currency',
        ),
        migrations.AddField(
            model_name='letting',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
