# Generated by Django 2.1.4 on 2019-02-14 22:35

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='defaulting_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, editable=False, help_text='Total amount defaulted for this letting (in Naira)', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='letting',
            name='defaulting_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='letting',
            name='defaulting_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
