# Generated by Django 2.1.4 on 2019-02-21 20:49

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letting',
            name='defaulting_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Total amount defaulted for this letting (in Naira)', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='letting',
            name='schedule_type',
            field=models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('single', 'Single')], help_text='Monthly, Quarterly or Annually', max_length=100),
        ),
        migrations.AlterField(
            model_name='letting',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('lease', 'Lease'), ('sale', 'Sale')], default='Rent', max_length=50),
        ),
    ]
