# Generated by Django 2.1.4 on 2019-02-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, choices=[('Lagos', 'lagos'), ('Port Harcourt', 'portharcourt')], max_length=100, null=True),
        ),
    ]
