# Generated by Django 2.1.4 on 2019-02-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='tag',
            field=models.CharField(help_text='A tag name for this image', max_length=255),
        ),
    ]
