# Generated by Django 2.1.4 on 2019-02-27 02:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
