# Generated by Django 2.1.4 on 2019-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('retail', 'Retail')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, choices=[('lagos', 'Lagos'), ('portharcourt', 'Port Harcourt')], max_length=100, null=True),
        ),
    ]
