# Generated by Django 2.1.4 on 2019-03-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_previously_logged_in',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
