# Generated by Django 2.1.4 on 2019-03-14 22:03

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_pyale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Amount Due for this bill', max_digits=19)),
                ('payment_status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('billing_cycle', models.CharField(max_length=255)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='letting',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='core.Letting'),
        ),
    ]
