# Generated by Django 2.1.4 on 2019-03-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pyale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyInventory',
        ),
        migrations.AlterField(
            model_name='letting',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='core.Property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='propertyrunningcosts',
            name='realty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property', verbose_name='Property'),
        ),
    ]
