# Generated by Django 2.1.4 on 2019-03-17 00:42

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_pyale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyinventory',
            options={'verbose_name': 'Property Inventory', 'verbose_name_plural': 'Property Inventories'},
        ),
        migrations.AlterField(
            model_name='propertyinventory',
            name='cost_incurred',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=19, null=True),
        ),
    ]
