# Generated by Django 2.1.4 on 2019-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='date_paid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_address_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
