# Generated by Django 2.1.4 on 2019-03-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_pyale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='date_paid',
            new_name='transaction_date',
        ),
        migrations.AddField(
            model_name='bills',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='card_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='last4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='transaction_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
