# Generated by Django 2.1.4 on 2019-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_pyale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='payment_channel',
        ),
        migrations.AddField(
            model_name='bills',
            name='is_mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
