# Generated by Django 2.1.4 on 2019-04-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='display_property',
            field=models.BooleanField(default=True),
        ),
    ]
