# Generated by Django 2.1.4 on 2019-04-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_pyale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='display_property',
            new_name='active',
        ),
    ]
