# Generated by Django 2.1.4 on 2019-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='home_page',
            field=models.BooleanField(default=False, help_text='If checked, property will be displayed on homepage'),
        ),
    ]
