# Generated by Django 2.1.4 on 2019-05-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='letting',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
