# Generated by Django 2.1.4 on 2019-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_pyale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
