# Generated by Django 2.1.4 on 2019-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_pyale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='image_2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_details',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='tag',
            field=models.CharField(choices=[('thumbnail', 'Thumbnail'), ('gallery', 'Gallery')], help_text="A tag name for this image. A 'thumbnail' tag means the image is displayed with the property summary.A 'gallery' tag means the image is displayed in the property gallery. NOTE: YOU CAN ONLY HAVE ONE THUMBNAIL IMAGE PER PROPERTY", max_length=255),
        ),
    ]
