# Generated by Django 2.1.4 on 2019-05-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_pyale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='specs',
        ),
        migrations.AddField(
            model_name='property',
            name='summary',
            field=models.TextField(default='Pyale Properties', max_length=180),
            preserve_default=False,
        ),
    ]
