# Generated by Django 2.1.4 on 2019-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='document',
            field=models.FileField(help_text='File must be in PDF format', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='document',
            field=models.FileField(help_text='File must be in PDF format', upload_to=''),
        ),
    ]
