# Generated by Django 2.1.4 on 2019-05-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='summary',
            field=models.TextField(help_text='Maximum of 180 characters', max_length=180),
        ),
    ]
