# Generated by Django 2.1.4 on 2019-05-13 01:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_pyale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
