# Generated by Django 2.1.4 on 2019-06-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_pyale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='current_rental_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='current_rental_value_currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='net_revenue',
        ),
        migrations.RemoveField(
            model_name='property',
            name='net_revenue_currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_value_currency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rental_revenue',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rental_revenue_currency',
        ),
    ]
