# Generated by Django 2.1.4 on 2019-06-14 08:55

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_pyale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='current_rental_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Rental Value of Property in Naira for current year', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='current_rental_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='net_revenue',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Net Revenue is the difference between the Rental revenue and total running costs', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='net_revenue_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='property_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Value of Property in Naira', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_revenue',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Payable Revenue on property in Naira for current year', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_revenue_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
